### ISSUE TITLE
[Feat] : 커뮤니티 API 수정

### ISSUE THREAD

**Issue by Ryeolee** [Mojacknong/Mojacknong-Farmus-msa-community#11]
## ✏️ Description

커뮤니티 개발한 API 수정

## To-Do List

- [ ]  댓글 조회 API =>  게시글 정보 주기
- [ ]  이미지 업로드 시 (게시글 쓰기, 수정) 메소드 분리
- [ ] 내 게시글 API 요청 시 프로필 정보 제공 없애기
